### ISSUE TITLE
Hi I need some sign font

### ISSUE THREAD

**Issue by kidly1** [alephpi/jianzipu#1]
您好 我在做一个古琴的web输入demo 用到了您的字体, 您的项目是我目前能找到的(包括广陵神器和其他开源项目输入)中最好的方案了, 但是现在碰到一个问题 : 在用户选择输入时 需要显示一些基本的指法让用户选择, 再选弦位, 这样我就需要一些指法不含弦位的字符 比如抹(mo)这个字"木"和 "勾" "挑" 等 , 同作为古琴爱好兼程序爱好者,请大神有时间的时候再维护一下项目 感谢

**Comment by alephpi** [comment]
您好，感谢您对本项目的关注。
目前项目确实处于搁置状态，因为上游项目[HowardZorn/kage-engine](https://github.com/HowardZorn/kage-engine)处于搁置状态，导致在本地调试较不方便。核心渲染逻辑已经完成（包括基本指法的简单谱字和撮式谱字），旁注形式的小字原理简单将来会继续补足，额外指法将会作为补丁逐渐追加。本项目同样计划开发古琴减字谱的web输入方法。如果您的需求仅仅是这些字符，那么可以参考[这里](http://en.glyphwiki.org/wiki/Group:mpsuzuki2_%e5%8f%a4%e7%90%b4%e6%b8%9b%e5%ad%97%e8%ad%9c)，本项目的基础部件都源于此。
