### ISSUE TITLE
Glyphs app

### ISSUE THREAD

**Issue by Sirius120794** [alephpi/jianzipu#2]
你好！冒昧打扰，我看您在介绍中说，如果开发或借助现有的造字引擎就可以解决显示方案。
我是程序小白，会弹古琴，字体设计初学者。目前学习字体设计用的是一款叫Glyphs的软件，https://glyphsapp.com/ 不知道这是不是您所说的造字引擎呢？我刚学还没摸透，但知道它是用Python写成的。
我比较认同您说的，减字的本质是一串短语，用unicode来穷举不太有意义。字体设计里有一种ligature，连字，原本是个拉丁字体里的概念，在中文字体设计里可以输入多个汉字出来一个方块字，好像并不是所有的连字都对应unicode（我并不确定）。
输入读法输出减字是个好主意，但这需要统一规范读法，毕竟中文一些词组颠来倒去可以表达一样的意思。我在想，顺序可不可以按照减字来，从上到下从左到右这种，毕竟读有很多种读法，写出来的字大部分比较统一就一个样子。
感谢！

**Comment by alephpi** [comment]
你好👋，感谢你对本项目的关注。

是的，我指的就是这种字体设计引擎。主要就是连字ligature的设计问题，这方面比较困难。你可以看看readme最上面提到的的unicode提案，里面有很详细的方案，不过其字体引擎是专利化的。

关于读法规范我设计的方案应该能覆盖常见情形，详见readme。
